# Generated by Django 3.2 on 2022-12-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_serverdb'),
        ('UserApp', '0002_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('status', models.IntegerField()),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.serverdb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.registrationdb')),
            ],
        ),
    ]
