# Generated by Django 3.2 on 2022-12-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TimeField()),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.cartdb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.registrationdb')),
            ],
        ),
    ]
