# Generated by Django 3.2 on 2022-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_bookingdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='total',
        ),
        migrations.RemoveField(
            model_name='registrationdb',
            name='name',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='date',
            field=models.DateField(default='2020-02-03'),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='time',
            field=models.TimeField(default='08:10:10'),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='lasttname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
