# Generated by Django 3.2 on 2022-12-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20221211_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
